# Generated by Django 4.1.7 on 2023-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productId',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='walletBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
