# Generated by Django 4.1.7 on 2023-04-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_ratingsmodel_rating_value'),
        ('merchants', '0002_rename_descriptiom_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='ecommerce_api.ratingsmodel'),
        ),
    ]
