# Generated by Django 4.1.7 on 2023-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_rename_status_productmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='walletBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
