# Generated by Django 4.1.7 on 2023-04-10 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='walletBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.TextField(blank=True)),
                ('productName', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('ratings', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
