# Generated by Django 4.1.7 on 2023-04-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0002_ratingsmodel_userprofile_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsmodel',
            name='rating_value',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
