# Generated by Django 4.1.7 on 2023-04-12 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_api', '0004_ratingsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='ratings',
        ),
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.TextField(blank=True)),
                ('productName', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
