# Generated by Django 4.1.7 on 2023-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0005_remove_cartmodel_ratings_checkoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
