# Generated by Django 4.1.7 on 2023-04-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0006_checkoutmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
